apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  namespace: roboshop
  labels: 
    app: catalogue
    tier: app
spec:
  replicas: 1
  selector:
    matchLabels: # these labels should match with pod
      app: catalogue
      tier: app
  template: # this is the pod definition
    metadata:
      labels:
        app: catalogue
        tier: app
    spec:
      containers:
      - name: catalogue
        image: "gspvsr/catalogue:{{ .Values.deployment.imageVersion}}"
        resources:
          requests:
            cpu: "50m"
            memory: "68Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
        envFrom:
        - configMapRef:
            name: catalogue
